'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace ServicesFleetStar
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProcesosFleetStarSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SolicitudCredito)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(InformacionEDS))>  _
    Partial Public Class ProcesosFleetStar
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private credencialValueField As Credencial
        
        Private RegistrarVentaCombustibleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SolicitarAutorizacionCreditoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LiberarCupoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarInicioTurnoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarCierreTurnoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ServicioComunicadorPetromil.My.MySettings.Default.ServicioComunicadorPetromil_ServicesFleetStar_ProcesosFleetStar
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property CredencialValue() As Credencial
            Get
                Return Me.credencialValueField
            End Get
            Set
                Me.credencialValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegistrarVentaCombustibleCompleted As RegistrarVentaCombustibleCompletedEventHandler
        
        '''<remarks/>
        Public Event SolicitarAutorizacionCreditoCompleted As SolicitarAutorizacionCreditoCompletedEventHandler
        
        '''<remarks/>
        Public Event LiberarCupoCompleted As LiberarCupoCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarInicioTurnoCompleted As RegistrarInicioTurnoCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarCierreTurnoCompleted As RegistrarCierreTurnoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CredencialValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarVentaCombustible", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarVentaCombustible(ByVal venta As VentaCombustible) As ResultadoSolicitud
            Dim results() As Object = Me.Invoke("RegistrarVentaCombustible", New Object() {venta})
            Return CType(results(0),ResultadoSolicitud)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaCombustibleAsync(ByVal venta As VentaCombustible)
            Me.RegistrarVentaCombustibleAsync(venta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarVentaCombustibleAsync(ByVal venta As VentaCombustible, ByVal userState As Object)
            If (Me.RegistrarVentaCombustibleOperationCompleted Is Nothing) Then
                Me.RegistrarVentaCombustibleOperationCompleted = AddressOf Me.OnRegistrarVentaCombustibleOperationCompleted
            End If
            Me.InvokeAsync("RegistrarVentaCombustible", New Object() {venta}, Me.RegistrarVentaCombustibleOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarVentaCombustibleOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarVentaCombustibleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarVentaCombustibleCompleted(Me, New RegistrarVentaCombustibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CredencialValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitarAutorizacionCredito", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SolicitarAutorizacionCredito(ByVal solicitud As SolicitudVentaCredito) As ResultadoAutorizacion
            Dim results() As Object = Me.Invoke("SolicitarAutorizacionCredito", New Object() {solicitud})
            Return CType(results(0),ResultadoAutorizacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SolicitarAutorizacionCreditoAsync(ByVal solicitud As SolicitudVentaCredito)
            Me.SolicitarAutorizacionCreditoAsync(solicitud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SolicitarAutorizacionCreditoAsync(ByVal solicitud As SolicitudVentaCredito, ByVal userState As Object)
            If (Me.SolicitarAutorizacionCreditoOperationCompleted Is Nothing) Then
                Me.SolicitarAutorizacionCreditoOperationCompleted = AddressOf Me.OnSolicitarAutorizacionCreditoOperationCompleted
            End If
            Me.InvokeAsync("SolicitarAutorizacionCredito", New Object() {solicitud}, Me.SolicitarAutorizacionCreditoOperationCompleted, userState)
        End Sub
        
        Private Sub OnSolicitarAutorizacionCreditoOperationCompleted(ByVal arg As Object)
            If (Not (Me.SolicitarAutorizacionCreditoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SolicitarAutorizacionCreditoCompleted(Me, New SolicitarAutorizacionCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CredencialValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LiberarCupo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LiberarCupo(ByVal codigoEDS As String, ByVal idAutorizacion As Integer) As ResultadoSolicitud
            Dim results() As Object = Me.Invoke("LiberarCupo", New Object() {codigoEDS, idAutorizacion})
            Return CType(results(0),ResultadoSolicitud)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LiberarCupoAsync(ByVal codigoEDS As String, ByVal idAutorizacion As Integer)
            Me.LiberarCupoAsync(codigoEDS, idAutorizacion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LiberarCupoAsync(ByVal codigoEDS As String, ByVal idAutorizacion As Integer, ByVal userState As Object)
            If (Me.LiberarCupoOperationCompleted Is Nothing) Then
                Me.LiberarCupoOperationCompleted = AddressOf Me.OnLiberarCupoOperationCompleted
            End If
            Me.InvokeAsync("LiberarCupo", New Object() {codigoEDS, idAutorizacion}, Me.LiberarCupoOperationCompleted, userState)
        End Sub
        
        Private Sub OnLiberarCupoOperationCompleted(ByVal arg As Object)
            If (Not (Me.LiberarCupoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LiberarCupoCompleted(Me, New LiberarCupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CredencialValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarInicioTurno", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarInicioTurno(ByVal turno As Turno) As ResultadoSolicitud
            Dim results() As Object = Me.Invoke("RegistrarInicioTurno", New Object() {turno})
            Return CType(results(0),ResultadoSolicitud)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarInicioTurnoAsync(ByVal turno As Turno)
            Me.RegistrarInicioTurnoAsync(turno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarInicioTurnoAsync(ByVal turno As Turno, ByVal userState As Object)
            If (Me.RegistrarInicioTurnoOperationCompleted Is Nothing) Then
                Me.RegistrarInicioTurnoOperationCompleted = AddressOf Me.OnRegistrarInicioTurnoOperationCompleted
            End If
            Me.InvokeAsync("RegistrarInicioTurno", New Object() {turno}, Me.RegistrarInicioTurnoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarInicioTurnoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarInicioTurnoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarInicioTurnoCompleted(Me, New RegistrarInicioTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("CredencialValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarCierreTurno", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarCierreTurno(ByVal turno As Turno) As ResultadoSolicitud
            Dim results() As Object = Me.Invoke("RegistrarCierreTurno", New Object() {turno})
            Return CType(results(0),ResultadoSolicitud)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarCierreTurnoAsync(ByVal turno As Turno)
            Me.RegistrarCierreTurnoAsync(turno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarCierreTurnoAsync(ByVal turno As Turno, ByVal userState As Object)
            If (Me.RegistrarCierreTurnoOperationCompleted Is Nothing) Then
                Me.RegistrarCierreTurnoOperationCompleted = AddressOf Me.OnRegistrarCierreTurnoOperationCompleted
            End If
            Me.InvokeAsync("RegistrarCierreTurno", New Object() {turno}, Me.RegistrarCierreTurnoOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarCierreTurnoOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarCierreTurnoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarCierreTurnoCompleted(Me, New RegistrarCierreTurnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Partial Public Class Credencial
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usuarioField As String
        
        Private claveField As String
        
        Private codigoEDSField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set
                Me.claveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoEDS() As String
            Get
                Return Me.codigoEDSField
            End Get
            Set
                Me.codigoEDSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleMaterialCredito
        
        Private codigoMaterialField As String
        
        Private precioField As Double
        
        '''<remarks/>
        Public Property CodigoMaterial() As String
            Get
                Return Me.codigoMaterialField
            End Get
            Set
                Me.codigoMaterialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Double
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleConsumo
        
        Private diaField As Double
        
        Private semanaField As Double
        
        Private mesField As Double
        
        '''<remarks/>
        Public Property Dia() As Double
            Get
                Return Me.diaField
            End Get
            Set
                Me.diaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Semana() As Double
            Get
                Return Me.semanaField
            End Get
            Set
                Me.semanaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mes() As Double
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleVisita
        
        Private diaField As Integer
        
        Private semanaField As Integer
        
        Private mesField As Integer
        
        '''<remarks/>
        Public Property Dia() As Integer
            Get
                Return Me.diaField
            End Get
            Set
                Me.diaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Semana() As Integer
            Get
                Return Me.semanaField
            End Get
            Set
                Me.semanaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mes() As Integer
            Get
                Return Me.mesField
            End Get
            Set
                Me.mesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResultadoAutorizacion
        
        Private tipoField As TipoTransaccion
        
        Private idAutorizacionField As Integer
        
        Private codigoClienteField As String
        
        Private nombreClienteField As String
        
        Private placaField As String
        
        Private cupoField As Double
        
        Private saldoField As Double
        
        Private mensajeField As String
        
        Private visitaField As DetalleVisita
        
        Private consumoField As DetalleConsumo
        
        Private detallesField() As DetalleMaterialCredito
        
        Private descuentoField As Double
        
        Private precioVentaClienteField As Double
        
        Private precioVentaEDSField As Double
        
        Private responsableCreditoField As String
        
        Private imprimirGuiaDespachoField As Boolean
        
        Private usaManifiestoField As Boolean
        
        '''<remarks/>
        Public Property Tipo() As TipoTransaccion
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdAutorizacion() As Integer
            Get
                Return Me.idAutorizacionField
            End Get
            Set
                Me.idAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoCliente() As String
            Get
                Return Me.codigoClienteField
            End Get
            Set
                Me.codigoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                Me.nombreClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cupo() As Double
            Get
                Return Me.cupoField
            End Get
            Set
                Me.cupoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Saldo() As Double
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Visita() As DetalleVisita
            Get
                Return Me.visitaField
            End Get
            Set
                Me.visitaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Consumo() As DetalleConsumo
            Get
                Return Me.consumoField
            End Get
            Set
                Me.consumoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Detalles() As DetalleMaterialCredito()
            Get
                Return Me.detallesField
            End Get
            Set
                Me.detallesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descuento() As Double
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioVentaCliente() As Double
            Get
                Return Me.precioVentaClienteField
            End Get
            Set
                Me.precioVentaClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioVentaEDS() As Double
            Get
                Return Me.precioVentaEDSField
            End Get
            Set
                Me.precioVentaEDSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponsableCredito() As String
            Get
                Return Me.responsableCreditoField
            End Get
            Set
                Me.responsableCreditoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImprimirGuiaDespacho() As Boolean
            Get
                Return Me.imprimirGuiaDespachoField
            End Get
            Set
                Me.imprimirGuiaDespachoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsaManifiesto() As Boolean
            Get
                Return Me.usaManifiestoField
            End Get
            Set
                Me.usaManifiestoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoTransaccion
        
        '''<remarks/>
        Niguna
        
        '''<remarks/>
        Credito
        
        '''<remarks/>
        Anticipo
        
        '''<remarks/>
        Control
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(SolicitudVentaCredito)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class SolicitudCredito
        
        Private codigoEDSField As String
        
        Private tipoIdentificadorField As TipoIdentificador
        
        Private numeroIdentificadorField As String
        
        Private manifiestoField As String
        
        Private codigoPosicionField As String
        
        '''<remarks/>
        Public Property CodigoEDS() As String
            Get
                Return Me.codigoEDSField
            End Get
            Set
                Me.codigoEDSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIdentificador() As TipoIdentificador
            Get
                Return Me.tipoIdentificadorField
            End Get
            Set
                Me.tipoIdentificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroIdentificador() As String
            Get
                Return Me.numeroIdentificadorField
            End Get
            Set
                Me.numeroIdentificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Manifiesto() As String
            Get
                Return Me.manifiestoField
            End Get
            Set
                Me.manifiestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPosicion() As String
            Get
                Return Me.codigoPosicionField
            End Get
            Set
                Me.codigoPosicionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoIdentificador
        
        '''<remarks/>
        Chip
        
        '''<remarks/>
        Tag
        
        '''<remarks/>
        CodigoBarras
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SolicitudVentaCredito
        Inherits SolicitudCredito
        
        Private placaField As String
        
        Private kilometrajeField As Double
        
        Private codigoMaterialField As String
        
        Private requiereAprobacionField As Boolean
        
        Private fechaSolicitudField As Date
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kilometraje() As Double
            Get
                Return Me.kilometrajeField
            End Get
            Set
                Me.kilometrajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoMaterial() As String
            Get
                Return Me.codigoMaterialField
            End Get
            Set
                Me.codigoMaterialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequiereAprobacion() As Boolean
            Get
                Return Me.requiereAprobacionField
            End Get
            Set
                Me.requiereAprobacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaSolicitud() As Date
            Get
                Return Me.fechaSolicitudField
            End Get
            Set
                Me.fechaSolicitudField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResultadoSolicitud
        
        Private mensajeField As String
        
        Private estadoField As EstadoSolicitud
        
        Private respuestaField As Object
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As EstadoSolicitud
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Respuesta() As Object
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum EstadoSolicitud
        
        '''<remarks/>
        Procesado
        
        '''<remarks/>
        [Error]
        
        '''<remarks/>
        Ninguno
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PosicionTurno
        
        Private codigoPosicionField As String
        
        Private lecturaField As Double
        
        Private precioField As Double
        
        '''<remarks/>
        Public Property CodigoPosicion() As String
            Get
                Return Me.codigoPosicionField
            End Get
            Set
                Me.codigoPosicionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lectura() As Double
            Get
                Return Me.lecturaField
            End Get
            Set
                Me.lecturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Double
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleVentaMaterial
        
        Private codigoMaterialField As String
        
        Private cantidadField As Double
        
        Private precioField As Double
        
        Private totalField As Double
        
        '''<remarks/>
        Public Property CodigoMaterial() As String
            Get
                Return Me.codigoMaterialField
            End Get
            Set
                Me.codigoMaterialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cantidad() As Double
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Precio() As Double
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Double
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FormaPago
        
        Private codigoSAPField As Integer
        
        Private codigoSapNuevoField As Integer
        
        Private nombreField As String
        
        Private valorField As Double
        
        Private numeroComprobanteField As String
        
        Private numeroAprobacionField As String
        
        Private numeroDocumentoField As String
        
        '''<remarks/>
        Public Property CodigoSAP() As Integer
            Get
                Return Me.codigoSAPField
            End Get
            Set
                Me.codigoSAPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoSapNuevo() As Integer
            Get
                Return Me.codigoSapNuevoField
            End Get
            Set
                Me.codigoSapNuevoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As Double
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroComprobante() As String
            Get
                Return Me.numeroComprobanteField
            End Get
            Set
                Me.numeroComprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroAprobacion() As String
            Get
                Return Me.numeroAprobacionField
            End Get
            Set
                Me.numeroAprobacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Turno)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Venta)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(VentaCombustible)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class InformacionEDS
        
        Private codigoEDSField As String
        
        '''<remarks/>
        Public Property CodigoEDS() As String
            Get
                Return Me.codigoEDSField
            End Get
            Set
                Me.codigoEDSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Turno
        Inherits InformacionEDS
        
        Private codigoTurnoField As Integer
        
        Private identificacionVendedorField As String
        
        Private totalConsignadoField As Double
        
        Private posicionesTurnoField() As PosicionTurno
        
        Private fechaHoraField As Date
        
        '''<remarks/>
        Public Property CodigoTurno() As Integer
            Get
                Return Me.codigoTurnoField
            End Get
            Set
                Me.codigoTurnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionVendedor() As String
            Get
                Return Me.identificacionVendedorField
            End Get
            Set
                Me.identificacionVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalConsignado() As Double
            Get
                Return Me.totalConsignadoField
            End Get
            Set
                Me.totalConsignadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PosicionesTurno() As PosicionTurno()
            Get
                Return Me.posicionesTurnoField
            End Get
            Set
                Me.posicionesTurnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaHora() As Date
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(VentaCombustible)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class Venta
        Inherits InformacionEDS
        
        Private idTurnoHorarioField As Integer
        
        Private idCorteTVField As Integer
        
        Private numeroDocumentoField As String
        
        Private identificacionVendedorField As String
        
        Private totalVentaField As Double
        
        Private numeroIdentificadorField As String
        
        Private idAutorizacionField As Integer
        
        Private formasPagoField() As FormaPago
        
        Private detalleVentaMaterialField() As DetalleVentaMaterial
        
        '''<remarks/>
        Public Property IdTurnoHorario() As Integer
            Get
                Return Me.idTurnoHorarioField
            End Get
            Set
                Me.idTurnoHorarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdCorteTV() As Integer
            Get
                Return Me.idCorteTVField
            End Get
            Set
                Me.idCorteTVField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdentificacionVendedor() As String
            Get
                Return Me.identificacionVendedorField
            End Get
            Set
                Me.identificacionVendedorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalVenta() As Double
            Get
                Return Me.totalVentaField
            End Get
            Set
                Me.totalVentaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroIdentificador() As String
            Get
                Return Me.numeroIdentificadorField
            End Get
            Set
                Me.numeroIdentificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdAutorizacion() As Integer
            Get
                Return Me.idAutorizacionField
            End Get
            Set
                Me.idAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FormasPago() As FormaPago()
            Get
                Return Me.formasPagoField
            End Get
            Set
                Me.formasPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DetalleVentaMaterial() As DetalleVentaMaterial()
            Get
                Return Me.detalleVentaMaterialField
            End Get
            Set
                Me.detalleVentaMaterialField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class VentaCombustible
        Inherits Venta
        
        Private codigoPosicionField As String
        
        Private idTurnoField As Integer
        
        Private ventaManualField As Boolean
        
        Private fechaHoraInicioField As Date
        
        Private fechaHoraFinField As Date
        
        Private lecturaInicialField As Double
        
        Private lecturaFinalField As Double
        
        Private placaField As String
        
        Private kilometrajeField As Double
        
        Private numeroManifiestoField As String
        
        Private responsableCreditoField As String
        
        Private precioVentaClienteField As Double
        
        Private precioVentaEDSField As Double
        
        '''<remarks/>
        Public Property CodigoPosicion() As String
            Get
                Return Me.codigoPosicionField
            End Get
            Set
                Me.codigoPosicionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdTurno() As Integer
            Get
                Return Me.idTurnoField
            End Get
            Set
                Me.idTurnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VentaManual() As Boolean
            Get
                Return Me.ventaManualField
            End Get
            Set
                Me.ventaManualField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaHoraInicio() As Date
            Get
                Return Me.fechaHoraInicioField
            End Get
            Set
                Me.fechaHoraInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaHoraFin() As Date
            Get
                Return Me.fechaHoraFinField
            End Get
            Set
                Me.fechaHoraFinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaInicial() As Double
            Get
                Return Me.lecturaInicialField
            End Get
            Set
                Me.lecturaInicialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LecturaFinal() As Double
            Get
                Return Me.lecturaFinalField
            End Get
            Set
                Me.lecturaFinalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Placa() As String
            Get
                Return Me.placaField
            End Get
            Set
                Me.placaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Kilometraje() As Double
            Get
                Return Me.kilometrajeField
            End Get
            Set
                Me.kilometrajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroManifiesto() As String
            Get
                Return Me.numeroManifiestoField
            End Get
            Set
                Me.numeroManifiestoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponsableCredito() As String
            Get
                Return Me.responsableCreditoField
            End Get
            Set
                Me.responsableCreditoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioVentaCliente() As Double
            Get
                Return Me.precioVentaClienteField
            End Get
            Set
                Me.precioVentaClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrecioVentaEDS() As Double
            Get
                Return Me.precioVentaEDSField
            End Get
            Set
                Me.precioVentaEDSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub RegistrarVentaCombustibleCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarVentaCombustibleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarVentaCombustibleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoSolicitud)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub SolicitarAutorizacionCreditoCompletedEventHandler(ByVal sender As Object, ByVal e As SolicitarAutorizacionCreditoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SolicitarAutorizacionCreditoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoAutorizacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoAutorizacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub LiberarCupoCompletedEventHandler(ByVal sender As Object, ByVal e As LiberarCupoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LiberarCupoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoSolicitud)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub RegistrarInicioTurnoCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarInicioTurnoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarInicioTurnoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoSolicitud)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub RegistrarCierreTurnoCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarCierreTurnoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarCierreTurnoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultadoSolicitud
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultadoSolicitud)
            End Get
        End Property
    End Class
End Namespace
